baseURL = "https://mystifying-lamarr-56b4de.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="des"
DefaultContentLanguage = "fr"

# Site Menus
[languages]

[languages.en]
[[languages.en.menu.main]]
identifier = "exterior"
name = "EXTERIOR DESIGN"
weight = 1
[languages.en.menu.main.params]
    class = 'highlight-menu-item'
    item=525
    check="exterior"

[[languages.en.menu.main]]
identifier = "landscaping"
name = "landscaping"
weight = 1
url = "/en/exterior_design/landscaping/"
parent = "exterior"
[languages.en.menu.main.params]
    item=530
    check="landscaping"

[[languages.en.menu.main]]
identifier = "masonry"
name = "masonry"
weight = 2
url = "/en/exterior_design/masonry/"
parent = "exterior"
[languages.en.menu.main.params]
    item=529
    check="masonry"

[[languages.en.menu.main]]
identifier = "retaining_wall"
name = "Retaining walls"
weight = 3
url = "/en/exterior_design/retaining_wall/"
parent = "exterior"
[languages.en.menu.main.params]
    item=528
    check="retaining_wall"


[[languages.en.menu.main]]
identifier = "pave_uni"
name = "pave-uni"
weight = 4
url = "/en/exterior_design/pave_uni/"
parent = "exterior"
[languages.en.menu.main.params]
    item=527
    check="pave_uni"


[[languages.en.menu.main]]
identifier = "stone_cutting"
name = "Stone cutting"
weight = 5
url = "/en/exterior_design/stone_cutting/"
parent = "exterior"
[languages.en.menu.main.params]
    item=526
    check="stone_cutting"

[[languages.en.menu.main]]
identifier = "expertise"
name = "EXPERTISE"
weight = 2
url = "/en/expertise/"
[languages.en.menu.main.params]
    item=121

[[languages.en.menu.main]]
identifier = "portfolio"
name = "PORTFOLIO"
weight = 3
url = "/en/portfolio/"
[languages.en.menu.main.params]
    item=374

[[languages.en.menu.main]]
identifier = "trends"
name = "TRENDS"
weight = 4
url = "/en/trends/"
[languages.en.menu.main.params]
    item=142

[[languages.en.menu.main]]
identifier = "careers"
name = "CAREERS"
weight = 5
url = "/en/careers/"
[languages.en.menu.main.params]
    item=904

[[languages.en.menu.main]]
identifier = "contact"
name = "CONTACT"
weight = 6
url = "/en/contact/"
[languages.en.menu.main.params]
    item=188







[languages.fr]
[[languages.fr.menu.main]]
identifier = "exterior"
name = "AMÉNAGEMENT EXTÉRIEUR"
weight = 1
[languages.fr.menu.main.params]
    class = 'highlight-menu-item'
    item=525


[[languages.fr.menu.main]]
identifier = "landscaping"
name = "Aménagement d’espace nature"
weight = 1
url = "/amenagement-exterieur/amenagement-despace-nature/"
parent = "exterior"
[languages.fr.menu.main.params]
    item=530


[[languages.fr.menu.main]]
identifier = "masonry"
name = "Maçonnerie"
weight = 2
url = "/amenagement-exterieur/maconnerie/"
parent = "exterior"
[languages.fr.menu.main.params]
    item=529

[[languages.fr.menu.main]]
identifier = "retaining_wall"
name = "Muret"
weight = 3
url = "/amenagement-exterieur/Muret/"
parent = "exterior"
[languages.fr.menu.main.params]
    item=528


[[languages.fr.menu.main]]
identifier = "pave_uni"
name = "Pavé uni"
weight = 4
url = "/amenagement-exterieur/pave-uni/"
parent = "exterior"
[languages.fr.menu.main.params]
    item=527

[[languages.fr.menu.main]]
identifier = "stone_cutting"
name = "Taille de pierre"
weight = 5
url = "/amenagement-exterieur/Taille de pierre/"
parent = "exterior"
[languages.fr.menu.main.params]
    item=526

[[languages.fr.menu.main]]
identifier = "expertise"
name = "EXPERTISE"
weight = 2
url = "/expertise/"
[languages.fr.menu.main.params]
    item=121

[[languages.fr.menu.main]]
identifier = "portfolio"
name = "PORTFOLIO"
weight = 3
url = "/portfolio/"
[languages.fr.menu.main.params]
    item=374

[[languages.fr.menu.main]]
identifier = "trends"
name = "TENDANCES"
weight = 4
url = "/tendances/"
[languages.fr.menu.main.params]
    item=142

[[languages.fr.menu.main]]
identifier = "careers"
name = "CARRIÈRES"
weight = 5
url = "/careers/"
[languages.fr.menu.main.params]
    item=904

[[languages.fr.menu.main]]
identifier = "contact"
name = "CONTACT"
weight = 6
url = "/contact/"
[languages.fr.menu.main.params]
    item=188
