baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="des"
DefaultContentLanguage = "fr"

# Site Menus
[languages]

[languages.en]
[[languages.en.menu.main]]
name = "EXTERIOR DESIGN"
weight = 1
url ="/exterior_design/"
[languages.en.menu.main.params]
    class = 'highlight-menu-item'
    item=525

[[languages.en.menu.main]]
name = "landscaping"
weight = 1
url = "/en/exterior_design/landscaping/"
parent = "EXTERIOR DESIGN"
[languages.en.menu.main.params]
    item=530

[[languages.en.menu.main]]
name = "masonry"
weight = 2
url = "/en/exterior_design/masonry/"
parent = "EXTERIOR DESIGN"
[languages.en.menu.main.params]
    item=529

[[languages.en.menu.main]]
name = "Retaining walls"
weight = 3
url = "/en/exterior_design/retaining_wall/"
parent = "EXTERIOR DESIGN"
[languages.en.menu.main.params]
    item=528


[[languages.en.menu.main]]
name = "pave-uni"
weight = 4
url = "/en/exterior_design/pave_uni/"
parent = "EXTERIOR DESIGN"
[languages.en.menu.main.params]
    item=527


[[languages.en.menu.main]]
name = "Stone cutting"
weight = 5
url = "/en/exterior_design/stone_cutting/"
parent = "EXTERIOR DESIGN"
[languages.en.menu.main.params]
    item=526

[[languages.en.menu.main]]
name = "EXPERTISE"
weight = 2
url = "/en/expertise/"
[languages.en.menu.main.params]
    item=121

[[languages.en.menu.main]]
name = "PORTFOLIO"
weight = 3
url = "/en/portfolio/"
[languages.en.menu.main.params]
    item=374

[[languages.en.menu.main]]
name = "TRENDS"
weight = 4
url = "/en/trends/"
[languages.en.menu.main.params]
    item=142

[[languages.en.menu.main]]
name = "CAREERS"
weight = 5
url = "/en/careers/"
[languages.en.menu.main.params]
    item=904

[[languages.en.menu.main]]
name = "CONTACT"
weight = 6
url = "/en/contact/"
[languages.en.menu.main.params]
    item=188







[languages.fr]
[[languages.fr.menu.main]]
name = "AMÉNAGEMENT EXTÉRIEUR"
weight = 1


[[languages.fr.menu.main]]
name = "Aménagement d’espace nature"
weight = 1
url = "/amenagement-exterieur/amenagement-despace-nature/"
parent = "AMÉNAGEMENT EXTÉRIEUR"


[[languages.fr.menu.main]]
name = "Maçonnerie"
weight = 2
url = "/amenagement-exterieur/maconnerie/"
parent = "AMÉNAGEMENT EXTÉRIEUR"

[[languages.fr.menu.main]]
name = "Muret"
weight = 3
url = "/amenagement-exterieur/Muret/"
parent = "AMÉNAGEMENT EXTÉRIEUR"

[[languages.fr.menu.main]]
name = "Pavé uni"
weight = 4
url = "/amenagement-exterieur/pave-uni/"
parent = "AMÉNAGEMENT EXTÉRIEUR"


[[languages.fr.menu.main]]
name = "Taille de pierre"
weight = 5
url = "/amenagement-exterieur/Taille de pierre/"
parent = "AMÉNAGEMENT EXTÉRIEUR"

[[languages.fr.menu.main]]
name = "EXPERTISE"
weight = 2
url = "/expertise/"

[[languages.fr.menu.main]]
name = "PORTFOLIO"
weight = 3
url = "/portfolio/"

[[languages.fr.menu.main]]
name = "TENDANCES"
weight = 4
url = "/tendances/"

[[languages.fr.menu.main]]
name = "CARRIÈRES"
weight = 5
url = "/careers/"

[[languages.fr.menu.main]]
name = "CONTACT"
weight = 6
url = "/contact/"
